FROM python:3.7.7-slim
  
COPY p2/bookinfo/src/productpage .

RUN apt-get update -y
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade requests
RUN pip3 install -r requirements.txt

EXPOSE 9080

CMD python3 productpage.py 9080

#sudo docker build -t equipo38/productpage .                                                        