version: '3.3'
services:
  productpage:
    image: equipo38/productpage:latest
    ports:
      - 9080:9080
    container_name: equipo38-productpage
    volumes:
      - productpage:/bookinfo/src/productpage

  details:
    image: equipo38/details:latest
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    container_name: equipo38-details
    depends_on:
      - productpage
    volumes:
      - details:/opt/microservices
    ports:
      - 9080
  reviews:
    image: equipo38/reviews:latest
    container_name: equipo38-reviews
    environment:
      - SERVERDIRNAME=reviews
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
      - STAR_COLOR=black
    depends_on:
      - productpage
    ports:
      - 9080
    volumes:
      - reviews:/opt/ibm/wlp/usr/servers/defaultServer

  ratings:
    image: equipo38/ratings:latest
    container_name: equipo38-ratings
    ports:
      - 9080
    environment:
            - SERVICE_VERSION=v1
    depends_on:
      - reviews
    volumes:
      - ratings:/opt/microservices

volumes:
  productpage:
  details:
  reviews:
  ratings: