FROM ruby:2.7.1-slim
  
COPY p2/bookinfo/src/details/details.rb /opt/microservices/

ENV SERVICE_VERSION=v1
ENV ENABLE_EXTERNAL_BOOK_SERVICE=true

EXPOSE 9080

WORKDIR /opt/microservices

CMD ruby details.rb 9080

#sudo docker build -t equipo38/details . 